#config
host: localhost
debug: false
post: 14444
mysql-host: 127.0.0.1
mysql-port: 3306
mysql-user: root
mysql-password:
mysql-database_data: nso_xxsx
mysql-database_ninja: nso_xxsx
max-level-up: 130
up-exp: 15
version-Data: 14
version-Map: 48
version-Skill: 13
version-Item: 13
version-Event: 4